apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wz1r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wz1r
    app.kubernetes.io/part-of: tkrw-pr712-0075-0066-app
  name: devfile-sample-wz1r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wz1r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wz1r
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0066-tenant/tkrw-pr712-0075-0066-app/devfile-sample-wz1r@sha256:0155fe2db01a4608150d0e3a379c8e04f90ceeda8c8b46db4ce9d1f93ab67052
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
